### ISSUE TITLE
Create `docker-compose.yml` file for deployment

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/hacktoberfest#11]
See https://github.com/teknologi-umum/pesto/blob/master/docker-compose.yml#L67-L123 for example

The app would be served by Traefik as the API gateway, so Traefik's label annotation should also be used.

The backend should resides on `/api` with the remove prefix middleware turned on and priority set to 2 (higher than frontend). The frontend should have `PathPrefix("/")` with priority set to 1. The `Host()` should be `hacktoberfest.teknologiumum.com`.

Add log limiter on each services:
```yaml
logging:
  driver: json-file
  options:
    max-size: 100M
    max-file: 3
```

Frontend must not depends on frontend. Both must implement healthchecks.
